### ISSUE TITLE
Delete instance confirmation shows the name of previously deleted instances

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/www-mastodon#77]
### Description

Delete instance confirmation shows the name of previously deleted instances, but then it goes away once you close and reopen the box again.

[Get Mastodon (20).webm](https://user-images.githubusercontent.com/101194226/205690980-609597f6-3758-4cdb-a8aa-03680f504ea8.webm)

**Comment by mohamedamer453** [comment]
I think the this is happening because not all contracts of the instance are being deleted, after deleting the instance shown in the video above

![image](https://user-images.githubusercontent.com/101194226/205695166-cc8135d9-4087-4994-881c-3d9059a62a01.png)

i found contracts related to this instance and to the other instance appeared in the box.

![image](https://user-images.githubusercontent.com/101194226/205695334-61af0359-2aee-4c0c-9d62-9cd1379bbae7.png)

it's similar to what was happening before in #43 but what's happening now is the reverse of this issue, the name and gateway contracts were deleted for both deployments but the node contract was not.

**Comment by Mahmoud-Emad** [comment]
@mohamedamer453 
The part related to deleting instance confirmation should be fixed in https://github.com/threefoldtech/www-mastodon/pull/84 and tested many times
While the part related to the contract deletions tested and confirmed on test net, look at the steps below

![image](https://user-images.githubusercontent.com/57001890/205916012-463a98b5-45ff-46f0-ab5e-95b871d97b6e.png)

![image](https://user-images.githubusercontent.com/57001890/205916099-6f3e3fe9-0330-4b29-b8c4-791cf1629cd3.png)

![image](https://user-images.githubusercontent.com/57001890/205916061-bb7c29d9-e47f-4a9f-a724-153192ab3bb7.png)

![image](https://user-images.githubusercontent.com/57001890/205916443-f1affe63-e0db-4dc6-86df-dc61bdd977bf.png)

**Comment by mohamedamer453** [comment]
The issue for the instance names was fixed and verified and the name of previously deleted instance doesn't appear anymore.

[Get Mastodon (25).webm](https://user-images.githubusercontent.com/101194226/206186009-a9aa440c-04bf-4676-b407-46a45e4a7479.webm)

**Comment by mohamedamer453** [comment]
The issue for the instance names was fixed and verified and the name of previously deleted instance doesn't appear anymore.

[Get Mastodon (25).webm](https://user-images.githubusercontent.com/101194226/206186009-a9aa440c-04bf-4676-b407-46a45e4a7479.webm)

**Comment by mohamedamer453** [comment]
> While the part related to the contract deletions tested and confirmed on test net, look at the steps below

However there's something still wrong with deletion, it worked with me correctly before as mentioned above in your comment and i was actually able to verify before that all the contract related to the deployment were deleted in https://github.com/threefoldtech/www-mastodon/issues/43#issuecomment-1336356600 . but sometimes it doesn't delete all the contracts and i happened three times in a row today so i'm not sure what the issue is.

### First instance

i didn't realize that the issue was happening so i wasn't able to get the logs or record the flow. but both the gateway and name contracts of this instance were not deleted.

![image](https://user-images.githubusercontent.com/101194226/206187092-b74d63f0-fe84-4fc3-8897-be5686b50a94.png)

### Second instance

I was able to get the console logs of the second one, and it shows that only the node contract was deleted and the other two contracts can also be seen in my contracts list.

```bash
Executing method: getTwinIdByAccountId with args: 5DV5mjx3u4u2Fe6NMmFS5ga523MHkdG4STsWABdD8kBcXUJW
Executing method: getContractByID with args: 11585
Sending {try 1}: https://gridproxy.grid.tf/twin/7
Sending {try 1}: Success
Object
Reading: https://gridproxy.grid.tf/twin/7/2399e2f2-a4a3-4c25-a414-2e3bffe63cc9
Executing method: getTwinIdByAccountId with args: 5DV5mjx3u4u2Fe6NMmFS5ga523MHkdG4STsWABdD8kBcXUJW
Validation succeed
Executing method: getTwinIdByAccountId with args: 5DV5mjx3u4u2Fe6NMmFS5ga523MHkdG4STsWABdD8kBcXUJW
Validation succeed
Executing method: getBalanceOf with args: 5DV5mjx3u4u2Fe6NMmFS5ga523MHkdG4STsWABdD8kBcXUJW
Executing method: getContractByID with args: 11585
Lock acquired
phase: {"applyExtrinsic":1}, section: balances, method: Withdraw
phase: {"applyExtrinsic":1}, section: smartContractModule, method: ContractBilled
phase: {"applyExtrinsic":1}, section: smartContractModule, method: NodeContractCanceled
phase: {"applyExtrinsic":1}, section: balances, method: Deposit
phase: {"applyExtrinsic":1}, section: system, method: ExtrinsicSuccess
Lock released
Executing method: getContractByID with args: 11585
```

![image](https://user-images.githubusercontent.com/101194226/206188721-830ebae1-081f-44ae-ba5a-6b683570946a.png)


### Third Instance

For the third instance i tried to record the whole flow including the contracts ids and the console logs, but the weird thing is that nothing appeared in the console logs and again only the node contract was deleted.

[Untitled_ Dec 7, 2022 2_55 PM.webm](https://user-images.githubusercontent.com/101194226/206187931-f1b42c3b-8bc7-4511-955a-787ba2654a8f.webm)

**Comment by Mahmoud-Emad** [comment]
@mohamedamer453 
You deleted one per one or deleted all at one push?
also, the console does not log anything in the third instance maybe because you added a link to your search bar maybe that was the reason.

![image](https://user-images.githubusercontent.com/57001890/206249141-252a4b26-203d-45ec-a200-e55e38f1b14b.png)

**Comment by mohamedamer453** [comment]
> @mohamedamer453 You deleted one per one or deleted all at one push?

Each instance was deleted independently as seen in the video for the third instance.

> also, the console does not log anything in the third instance maybe because you added a link to your search bar maybe that was the reason.
> 
> ![image](https://user-images.githubusercontent.com/57001890/206249141-252a4b26-203d-45ec-a200-e55e38f1b14b.png)

Yes, indeed i checked it again and it was due to the added link. i think it was due to the extension i used to record the screen.

**Comment by Mahmoud-Emad** [comment]
@mohamedamer453 

https://user-images.githubusercontent.com/57001890/206412337-e13c3acd-9893-4bf1-825a-5b58e3d038c5.mp4


I tried it many times and as you see in the recorded video all work well I deleted all instances that I deployed then after every instance was deleted I checked it contracts and I made sure all its deleted also, the only weird thing I notice the error message I got when debugging the second instance which is means the error is not from our code here in mastodon the same error in 
`playground QA net` and I opened an issue for it in https://github.com/threefoldtech/grid_weblets/issues/1166

![image](https://user-images.githubusercontent.com/57001890/206410444-65641279-ed66-4852-bd7b-54d265eb49a9.png)

but it does not block your deletion as you see at the end of the video all contracts were deleted!

**Comment by mohamedamer453** [comment]
I tried to reproduce it again with 6 different instances, the first 3 instances everything ran smoothly without any issues and all the contracts were deleted as seen below.

For the second 3 instances, i deleted the first one individually and it also went smoothly, i then deleted the other 2 together and they were also deleted and from the console logs everything appeared fine but when i reloaded the contracts list, all of the contracts were still there as seen in the video below.

https://user-images.githubusercontent.com/101194226/206436260-824f8df1-d5cb-4be3-840d-e523b806e30d.mp4

i then checked the contract from the chain and it was deleted, and from graphql its state was `Created`, however after a couple of mins i checked the contracts list again and the contracts were gone, and from graphql the state was changed to `Deleted`.

will close this for now since it's probably not an issue from mastodon, will keep an eye on future deployments and will report if there's any weird behavior with deletion.
